### ISSUE TITLE
Multiline action sheet

### ISSUE THREAD

**Issue by Adarkas2302** [ShiWeiCN/JESAlertView#1]
Is there a way to get a multiline action sheet? I Mean a multiline text for one option of the action sheet.

**Comment by Adarkas2302** [comment]
Tried the new Demo workspace. but the long long ;) titel button is not multiline the middle just gets turned to '...'. Do i have to do something special to get it to go multiline.

**Comment by ShiWeiCN** [comment]
Hi there, I'm sorry for delay. I have fixed this issue, but where I `pod trunk push`, I got one problem like [issue#6098](https://github.com/CocoaPods/CocoaPods/issues/6098) . So when this problem fixed I will upgrade **JESAlertView**.

**Comment by Adarkas2302** [comment]
ok thanks for the quick help.

**Comment by ShiWeiCN** [comment]
@Adarkas2302 That problem has been fixed. So, please `pod update` and you will see the multiline options of action sheet. 😊
